arminstructionrate: arminstructionrate.s arminstructionrate.c arminstructionrate.h
	aarch64-unknown-linux-gnu-gcc -march=armv8.5-a+memtag -O3 arminstructionrate.s arminstructionrate.c -o arminstructionrate -static-pie
